### ISSUE TITLE
New owner, what happen?

### ISSUE THREAD

**Issue by SydOps** [puppet-community/puppet-rundeck#39]
One hour before, I found puppet-rundeck has new release 1.1, and the repository name has been changed from `opentable/rundeck` to `puppet-community/puppet-rundeck`

Any updates for us?

**Comment by liamjbennett** [comment]
This module - along with a number of opentable modules are being migrated into the puppet-community organisation and forge namespace.

The TLDR; of this is so that we will be able to invite further contribution, gain help with maintenance and increase the overall quality.

There will be a couple of blog posts about this soon that will explain the decision in a little more detail.
